### ISSUE TITLE
Does not work on Linux because of webview2

### ISSUE THREAD

**Issue by CAABAG** [MarcellVokk/aio-launcher#2]
Webview2 is not supported on Linux. Therefore, I was unable to get the launcher working appropriately. Here's a quick rundown of my experience with the launcher:
1. The AiO Launcher launches
2. I download Rise of the Witch King
3. I click on the 'Multiplayer' tab
4. a new window pops up, I can interact with it, but the mouse position is off, and the window is immutable (I cannot move, resize, or minimize it at all)
5. I manage to open a room and launch the game, but the webview2 Multiplayer tab is still on my screen, covering about 2/3 of what's behind it, rendering the game unplayable

I installed and ran the launcher via Lutris ver. 0.5.17, using the wine-ge-8-26-x86_64 runner, on Linux Mint 21.3:
OS: Linux Mint 21.3 x86_64 
Host: MS-7C84 1.0 
Kernel: 5.15.0-126-generic 
Packages: 2943 (dpkg), 51 (flatpak) 
Shell: bash 5.1.16 
Resolution: 2560x1440 
DE: Cinnamon 
WM: Mutter (Muffin)
Terminal: gnome-terminal 
CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz 
GPU: NVIDIA GeForce RTX 3070 
Memory: 5887MiB / 32012MiB

Is there anything I can do about it? Is there anything you can do about it?

**Comment by MarcellVokk** [comment]
Hi! I'm not sure what you mean here, the multiplayer tab is not a webview...

It's a separate window running in a separate process (called Online Arena), that is the child window of the launcher. I assume whatever emulation layer or compatibility layer you are using doesn't support some of the windows apis the launcher calls to make the multiplayer arena window a child window.

I'd also like to point out that at this moment, we don't officialy support Linux, or any other operating system that's not windows 10 or later.

**Comment by CAABAG** [comment]
Unfortunately it does seem so, because as long as I can interact with the widgets within the window, the window itself seems to be unresponsive at all.

Are there any plans for supporting Linux in the future?

**Comment by CAABAG** [comment]
That's a shame. But the discord server sounds good.

Since there are no plans on supporting this launcher on Linux officially I suppose we can close this issue.
